title: Ankush Kaundal
url: "https://ankushkaundal.github.io"
baseurl: ""
markdown: kramdown
#ins_logo: "./bits-logo.png"
tracking_id: #
footer: yes
footer_url: "https://github.com/ankushkaundal"
footer_text: "Ankush Kaundal"
sass:
    style: compressed
    sass_dir: _sass
nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
