title: Ankush Kaundal
url: "https://ankushkaundal.github.io"
baseurl: ""
markdown: kramdown
#ins_logo: "./bits-logo.png"
tracking_id: #
footer: no
sass:
    style: compressed
    sass_dir: _sass
nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "publications"
 - name: "Projects"
   link: "projects"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
