title: Ankush Kaundal
url: "https://ankushkaundal.github.io"
baseurl: ""
markdown: kramdown
#ins_logo: "./bits-logo.png"
tracking_id: #
footer: no
sass:
    style: compressed
    sass_dir: _sass
nav:
 - name: "About"
   link: "/"
# - name: "publications"
 #  link: "publications" 
 - name: "projects"
   link: "projects"
 - name: "resume"
   link: "resume.pdf"
 - name: "contact"
   link: "contact"
